#pragma once
#include <windows.h>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <tchar.h>
#include <vector>
#include <random>
#include <fstream>
#include <time.h>
#include <string>
#include <thread>
#include <future>